name: Docker Image Build

on:
  push:
    branches: [ test-stable, community ]
  pull_request:
    branches: [ test-stable, community ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose images
        run: |
          docker compose build

      - name: Verify built image
        run: |
          docker images --format '{{.Repository}}:{{.Tag}}\t{{.Size}}' | grep 'ghcr.io/whit3str/diis-na-server:latest' || true
